### PR TITLE
Docs/6.2.1: Add model quantization doc fixes

### PR DESCRIPTION
**Pull request by peterjunpark**
publishes fixes in https://github.com/ROCm/ROCm/pull/3638

### CODE REVIEW

**Review by yhuiYH — APPROVED** [review]
LGTM

**Comment by yhuiYH** [comment]
@peterjunpark oh wait, should we just do a deveop -> docs/6.2.1 merge to update 6.2.1?

**Comment by peterjunpark** [comment]
Add #3668 when merged into develop

**Comment by peterjunpark** [comment]
This is done in #3669

**Pull request closed without merging**
