### PR TITLE
Update default.xml

### PR DESCRIPTION
**Pull request by JeniferC99**
Remove ROCT-Thunck-Interface
Add TransferBench
Add hipBLAS-common

### CODE REVIEW

**Review by dgaliffiAMD — COMMENTED** [review]
Do we need to add rocJPEG too? 

See: https://github.com/ROCm/ROCm/pull/4136

**Comment by peterjunpark** [comment]
I think `<project name="ROCT-Thunk-Interface" />` should be removed

**Comment by dgaliffiAMD** [comment]
> I think `<project name="ROCT-Thunk-Interface" />` should be removed

Thanks. I wasn't sure about that one.

**Comment by dgaliffiAMD** [comment]
Let's re-open, we still have to remove "ROCT-Thunk-Interface" from the manifest.

**Review by dgaliffiAMD — APPROVED** [review]

**Review by dgaliffiAMD — DISMISSED** [review]

**Comment by JeniferC99** [comment]
I think we need to add hipBLAS-common and TransferBench too

**Review by peterjunpark — APPROVED** [review]

**Pull request merged**
